# Generated by Django 2.2.7 on 2019-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sozluk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eng_tr',
            name='exam',
            field=models.CharField(default='', max_length=100, verbose_name='Örnek'),
        ),
        migrations.AlterField(
            model_name='eng_tr',
            name='eng',
            field=models.CharField(max_length=20, verbose_name='İngilizce'),
        ),
        migrations.AlterField(
            model_name='eng_tr',
            name='tr',
            field=models.CharField(max_length=20, verbose_name='Türkçe'),
        ),
    ]
